name: bloc_demo
description: A new Flutter application using bloc.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: any
  rxdart: ^0.18.1
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true

