name: bloc_demo
description: A new Flutter application using bloc.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^0.2.3
  rxdart: ^0.18.1
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 0.8.3
  json_serializable: 0.5.2

flutter:
  uses-material-design: true

